name: test

on:
  push:
    #paths:
    #  - 'oas.yaml'
    branches:
      - master
jobs:
  build:
    name: test
    runs-on: ubuntu-latest

    #container:
    #  image:  google/dart:latest
    container:
      image:  google/dart:2.7

    if: "! contains(github.event.head_commit.message, '[ci skip]') && ! contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v2
      #- name: install dart
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install apt-transport-https -y
      #    sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
      #    sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
      #    sudo apt-get update
      #    sudo apt-get install dart -y
      #    /usr/lib/dart/bin/dart --version
      - name: coffee
        run: ./tool/travis.sh analyze
        env:
          PKG: "example/coffee"
      - name: train
        run: ./tool/travis.sh analyze
        env:
          PKG: "example/train"
      - name: inject
        run: ./tool/travis.sh analyze
        env:
          PKG: "package/inject"
      - name: inject_generator
        run: ./tool/travis.sh analyze
        env:
          PKG: "package/inject_generator"